// especialidades.ts
const especialidades: string[] = [
    "Medicina Familiar",
    "Medicina Interna",
    "Pediatría",
    "Ginecología y Obstetricia",
    "Cirugía General",
    "Dermatología",
    "Cardiología",
    "Neurología",
    "Oncología",
    "Radiología",
    "Urología",
    "Otorrinolaringología",
    "Oftalmología",
    "Anestesiología",
    "Reumatología",
    "Endocrinología",
    "Infectología",
    "Traumatología y Ortopedia",
    "Nefrología",
    "Hematología",
    "Neumología",
    "Gastroenterología",
    "Psiquiatría",
    "Estomatología",
    "Odontología",
    "Medicina del Trabajo",
    "Cardiología Intervencionista",
    "Neurocirugía",
    "Oncología Radioterapéutica",
    "Gastroenterología Endoscópica",
    "Neonatología",
    "Cuidados Intensivos Pediátricos",
    "Endocrinología y Metabolismo",
    "Inmunología",
    "Medicina del Sueño",
    "Rehabilitación Médica",
    "Medicina de Emergencias",
    "Medicina del Deporte",
    "Medicina Legal",
    "Medicina Nuclear",
    "Medicina Preventiva",
    "Medicina del Viajero",
    "Medicina Ambiental",
    "Medicina de la Salud Mental Comunitaria",
    "Medicina de la Mujer",
    "Medicina Geriátrica"
  ];
  
  export default especialidades;